### ISSUE TITLE
Support Forum Unusable

### ISSUE THREAD

**Issue by bavoha** [publicrepo/gmscript#1]
Sorry to be a little off-topic, as said in the title I can not write to the official forum.

After writing a total legit posting in the official forum, my posting and my account there were completely deleted overnight. There was no spam, trolling or break of other rules in it and I received no further information.

If thats thats a dead-end, what way of contribution works?

**Comment by publicrepo** [comment]
My sincere apologies bavoha. I mistook your post for spam and deleted it.

I've unbaned and restored your account.  I can't undelete the post, however I do have a copy of the original text:

---

xstart is a script runtime for rapid software development based on gm-script.

http://www.xstart.io - For over 3-years in development now, this is the very first public release and it is currently in beta stage.

It already has a lot of features and is versatile enough to be used for tools, servers and frontends. Rendering is done through a OpenGL based scene-graph. Each node receives input in the form of callbacks (eg. onMouseDown, onMouseUp etc.). And there is much much more: Shaders, Advanced Audio, Image Detection, HTTP Server, UTF-8 Support ...

The package comes with a reference documentation, examples and a modified Scite editor to get you started. I also work on a quickstart guide too. The software runs on Windows, Linux and also Raspberry Pi. Installation instructions on Linux is provided here: https://gitlab.com/bavoha/xstart/wikis/home

---

Please try logging in again and feel free to re/post.  Let me know if you encounter any difficulties.
Once again, I'm very sorry for the slap in the face when you were just trying to share some coding goodness.

**Comment by bavoha** [comment]
So the forum isn't declared dead - that's good! I'll happily repost :)

And thank  you for gmscript which worked stable in almost 50 commercial projects so far and makes programming in xstart fun and easy.

**Comment by bavoha** [comment]
http://www.gmscript.com/gamemonkey/forum/viewtopic.php?f=14&t=634
