### ISSUE TITLE
Jit?

### ISSUE THREAD

**Issue by Shadowblitz16** [publicrepo/gmscript#8]
It would probably make this more popular if it was as fast as luajit.

**Comment by publicrepo** [comment]
Agreed, speed does sell in the world of scripting.
However I have no knowledge of active projects to add JIT support, including myself (I mostly make time for maintenance of this repo.)

**Comment by Shadowblitz16** [comment]
@publicrepo you could always archive this and create a new branch of gmscript and try to modify luajit.
